# Generated by Django 5.2.5 on 2025-08-31 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(help_text='Registro Acadêmico de 10 dígitos', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='RA deve conter exatamente 10 dígitos', regex='^\\d{10}$')], verbose_name='Registro Acadêmico')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('curso', models.CharField(choices=[('ENG_COMP', 'Engenharia da Computação'), ('CIENCIA_DADOS', 'Ciência de Dados'), ('TEC_INFO', 'Tecnologia da Informação'), ('MATEMATICA', 'Matemática'), ('FISICA', 'Física'), ('QUIMICA', 'Química'), ('BIOLOGIA', 'Biologia'), ('PEDAGOGIA', 'Pedagogia'), ('LETRAS', 'Letras'), ('ADMINISTRACAO', 'Administração')], max_length=20, verbose_name='Curso')),
                ('semestre_atual', models.PositiveIntegerField(help_text='Semestre que o aluno está cursando atualmente', verbose_name='Semestre Atual')),
                ('data_ingresso', models.DateField(help_text='Data de ingresso no curso', verbose_name='Data de Ingresso')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o aluno está ativo no curso', verbose_name='Ativo')),
                ('polo', models.CharField(blank=True, help_text='Polo de apoio presencial do aluno', max_length=100, null=True, verbose_name='Polo de Apoio')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome_completo'],
                'indexes': [models.Index(fields=['ra'], name='alunos_alun_ra_cd978d_idx'), models.Index(fields=['curso'], name='alunos_alun_curso_fca5b2_idx'), models.Index(fields=['ativo'], name='alunos_alun_ativo_26ee3e_idx')],
            },
        ),
    ]
